// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Settings.Infrastructure.Persistence;

#nullable disable

namespace Settings.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
<<<<<<<< HEAD:Settings.Infrastructure/Data/Migrations/20241227155710_Intial.Designer.cs
    [Migration("20241227155710_Intial")]
    partial class Intial
========
    [Migration("20241227100235_Initial")]
    partial class Initial
>>>>>>>> 61f98cdf5b9c3a2f4f3b3797f5f9094dab2ecaa1:Settings.Infrastructure/Data/Migrations/20241227100235_Initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Settings.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Applications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("DatatableRowLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmployeeCanExportData")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Settings.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("TaxName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("BusinessLocations");
                });

            modelBuilder.Entity("Settings.Domain.Entities.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BusinessTypes");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Settings.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegnNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractNumberDigits")
                        .HasColumnType("int");

                    b.Property<string>("ContractNumberExample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumberSeprator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecimalSeparator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExchangeRate")
                        .HasColumnType("int");

                    b.Property<string>("IsCryptocurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberofDecimals")
                        .HasColumnType("int");

                    b.Property<string>("ThousandSeparator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USDPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Settings.Domain.Entities.CustomQuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CQCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CQCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CustomQuestionCategories");
                });

            modelBuilder.Entity("Settings.Domain.Entities.CustomQuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CQTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CQTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CustomQuestionTypes");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("Settings.Domain.Entities.JobApplicationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JACategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JACategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobApplicationCategories");
                });

            modelBuilder.Entity("Settings.Domain.Entities.JobApplicationPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JAPositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JAPositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobApplicationPositions");
                });

            modelBuilder.Entity("Settings.Domain.Entities.LeadAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadAgents");
                });

            modelBuilder.Entity("Settings.Domain.Entities.LeadCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadCategories");
                });

            modelBuilder.Entity("Settings.Domain.Entities.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadSources");
                });

            modelBuilder.Entity("Settings.Domain.Entities.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("All")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowChatClientEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("Allowchatclientadmin")
                        .HasColumnType("bit");

                    b.Property<bool>("OnlyProjectMembercanwithclient")
                        .HasColumnType("bit");

                    b.Property<bool>("SoundNotifyAlert")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgentTicket")
<<<<<<<< HEAD:Settings.Infrastructure/Data/Migrations/20241227155710_Intial.Designer.cs
========
                        .HasColumnType("bit");

                    b.Property<bool>("AttendanceReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoTaskReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("EmployeeAssigntoProject")
                        .HasColumnType("bit");

                    b.Property<bool>("EstimateDeclined")
                        .HasColumnType("bit");

                    b.Property<bool>("EventInvite")
                        .HasColumnType("bit");

                    b.Property<bool>("EventReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("FollowUpReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("Leadnotification")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationAttendanceReminderNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationEventInviteNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationEventReminderNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationTestNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewClientTask")
                        .HasColumnType("bit");

                    b.Property<bool>("NewExpenseAddedbyAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("NewExpenseAddedbyMember")
                        .HasColumnType("bit");

                    b.Property<bool>("NewFileUploadedtoProject")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLeaveRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NewMultipleLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewNoticePublished")
                        .HasColumnType("bit");

                    b.Property<bool>("NewOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("NewPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProductPurchase")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProject")
                        .HasColumnType("bit");

                    b.Property<bool>("NewPropoInvoiceUpdatedsal")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProposal")
                        .HasColumnType("bit");

                    b.Property<bool>("NewRecurringInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("NewSupportTicketRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTask")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTicketReply")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTicketRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NoticeUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("OrderUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjectReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ProposalApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("ProposalRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("RecurringExpenseStatusUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("RecurringInvoiceStatusUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestAdminNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApprovedLead")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApprovedUser")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestReject")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestRejectLead")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestRejectUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTaskAssigneeAdded")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTaskCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskComment")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCompletedClient")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskNote")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskUpdateClient")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorCode")
                        .HasColumnType("bit");

                    b.Property<bool>("UserJoinViaInvitation")
                        .HasColumnType("bit");

                    b.Property<bool>("UserRegistrationAddedbyAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Settings.Domain.Entities.NotificationMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonNotificationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNotificationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
>>>>>>>> 61f98cdf5b9c3a2f4f3b3797f5f9094dab2ecaa1:Settings.Infrastructure/Data/Migrations/20241227100235_Initial.Designer.cs
                        .HasColumnType("bit");

                    b.Property<bool>("AttendanceReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoTaskReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("EmployeeAssigntoProject")
                        .HasColumnType("bit");

                    b.Property<bool>("EstimateDeclined")
                        .HasColumnType("bit");

                    b.Property<bool>("EventInvite")
                        .HasColumnType("bit");

                    b.Property<bool>("EventReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("FollowUpReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("Leadnotification")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationAttendanceReminderNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationEventInviteNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationEventReminderNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationTestNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewClientTask")
                        .HasColumnType("bit");

                    b.Property<bool>("NewExpenseAddedbyAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("NewExpenseAddedbyMember")
                        .HasColumnType("bit");

                    b.Property<bool>("NewFileUploadedtoProject")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLeaveRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NewMultipleLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewNoticePublished")
                        .HasColumnType("bit");

                    b.Property<bool>("NewOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("NewPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProductPurchase")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProject")
                        .HasColumnType("bit");

                    b.Property<bool>("NewPropoInvoiceUpdatedsal")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProposal")
                        .HasColumnType("bit");

                    b.Property<bool>("NewRecurringInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("NewSupportTicketRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTask")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTicketReply")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTicketRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NoticeUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("OrderUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjectReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ProposalApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("ProposalRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("RecurringExpenseStatusUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("RecurringInvoiceStatusUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestAdminNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApprovedLead")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApprovedUser")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestReject")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestRejectLead")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestRejectUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTaskAssigneeAdded")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTaskCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskComment")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCompletedClient")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskNote")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskUpdateClient")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorCode")
                        .HasColumnType("bit");

                    b.Property<bool>("UserJoinViaInvitation")
                        .HasColumnType("bit");

                    b.Property<bool>("UserRegistrationAddedbyAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NotificationMains");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Designation")
                        .HasColumnType("int");

                    b.Property<int>("Employee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<float>("PlanPrice")
                        .HasColumnType("real");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("Validity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.ProjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectCategories");
                });

            modelBuilder.Entity("Settings.Domain.Entities.ProjectReminderPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectReminderPersons");
                });

            modelBuilder.Entity("Settings.Domain.Entities.ProjectSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSendReminder")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectReminderPersonId")
                        .HasColumnType("int");

                    b.Property<int>("RemindBefore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectReminderPersonId")
                        .IsUnique();

                    b.ToTable("ProjectSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillOrderNumberDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillOrderNumberExample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillOrderNumberSeperater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillOrderPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNumberDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNumberExample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNumberSeperater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCreditNumberDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCreditNumberExample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCreditNumberSeperater")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCreditPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitCustomQuestionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CQIsRequiredId")
                        .HasColumnType("int");

                    b.Property<string>("CQQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CQStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomQuestionCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CustomQuestionTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomQuestionCategoryId");

                    b.HasIndex("CustomQuestionTypeId");

                    b.ToTable("RecruitCustomQuestionSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitFooterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FooterDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FooterStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FooterTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RecruitFooterSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitGeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralAboutCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralBGColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralBGLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralBGLogoImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralBGLogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCBJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCompanyLogoImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCompanyLogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCompanyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralDuplJobApplnRestrictDays")
                        .HasColumnType("int");

                    b.Property<string>("GeneralLegalTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralOLReminderToCandidate")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RecruitGeneralSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitJobApplicationStatusSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JASColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JASIsModelChecked")
                        .HasColumnType("int");

                    b.Property<string>("JASStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobApplicationCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobApplicationPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationCategoryId");

                    b.HasIndex("JobApplicationPositionId");

                    b.ToTable("RecruitJobApplicationStatusSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitNotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CBEMailJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBEMailNotificationJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RecruitNotificationSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruiterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RecruiterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecruiterStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RecruiterSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Settings.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddFile")
                        .HasColumnType("bit");

                    b.Property<int>("AfterXDate")
                        .HasColumnType("int");

                    b.Property<bool>("AssignedBy")
                        .HasColumnType("bit");

                    b.Property<bool>("AssignedTo")
                        .HasColumnType("bit");

                    b.Property<int>("BeforeXDate")
                        .HasColumnType("int");

                    b.Property<bool>("Comment")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyTaskLink")
                        .HasColumnType("bit");

                    b.Property<bool>("CustomFields")
                        .HasColumnType("bit");

                    b.Property<bool>("Description")
                        .HasColumnType("bit");

                    b.Property<bool>("DueDate")
                        .HasColumnType("bit");

                    b.Property<bool>("History")
                        .HasColumnType("bit");

                    b.Property<bool>("HoursLogged")
                        .HasColumnType("bit");

                    b.Property<bool>("Label")
                        .HasColumnType("bit");

                    b.Property<bool>("MakePrivate")
                        .HasColumnType("bit");

                    b.Property<bool>("Notes")
                        .HasColumnType("bit");

                    b.Property<bool>("Priority")
                        .HasColumnType("bit");

                    b.Property<bool>("Project")
                        .HasColumnType("bit");

                    b.Property<bool>("SendReminderDueDate")
                        .HasColumnType("bit");

                    b.Property<bool>("StartDate")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Statuss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SubTask")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCategory")
                        .HasColumnType("bit");

                    b.Property<int>("TaskboardLength")
                        .HasColumnType("int");

                    b.Property<bool>("TimeEstimate")
                        .HasColumnType("bit");

                    b.Property<bool>("Timesheet")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("Settings.Domain.Entities.TimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CBTimeLogJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDailyTimeLogReportEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeTrackerReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TLTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("TimeLogs");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Address", b =>
                {
                    b.HasOne("Settings.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Applications", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Currency", "Currency")
                        .WithMany("Applications")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Settings.Domain.Entities.BusinessLocation", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Company", "Company")
                        .WithMany("BusinessLocations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Settings.Domain.Entities.City", b =>
                {
                    b.HasOne("Settings.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Client", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Company", b =>
                {
                    b.HasOne("Settings.Domain.Entities.BusinessType", "BusinessType")
                        .WithMany("Companies")
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Category", "Category")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Department", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Designation", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Company", "Company")
                        .WithMany("Designations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Department", "Department")
                        .WithMany("Designations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Settings.Domain.Entities.ProjectSetting", b =>
                {
                    b.HasOne("Settings.Domain.Entities.ProjectReminderPerson", "ProjectReminderPerson")
                        .WithOne("ProjectSetting")
                        .HasForeignKey("Settings.Domain.Entities.ProjectSetting", "ProjectReminderPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectReminderPerson");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitCustomQuestionSetting", b =>
                {
                    b.HasOne("Settings.Domain.Entities.CustomQuestionCategory", "CustomQuestionCategory")
                        .WithMany("recruitCustomQuestionSettings")
                        .HasForeignKey("CustomQuestionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.CustomQuestionType", "CustomQuestionType")
                        .WithMany("recruitCustomQuestionSettings")
                        .HasForeignKey("CustomQuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomQuestionCategory");

                    b.Navigation("CustomQuestionType");
                });

            modelBuilder.Entity("Settings.Domain.Entities.RecruitJobApplicationStatusSetting", b =>
                {
                    b.HasOne("Settings.Domain.Entities.JobApplicationCategory", "JobApplicationCategory")
                        .WithMany("RecruitJobApplicationStatusSettings")
                        .HasForeignKey("JobApplicationCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.JobApplicationPosition", "JobApplicationPosition")
                        .WithMany("RecruitJobApplicationStatusSettings")
                        .HasForeignKey("JobApplicationPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplicationCategory");

                    b.Navigation("JobApplicationPosition");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Role", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Department", "Department")
                        .WithMany("Roles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settings.Domain.Entities.Designation", "Designation")
                        .WithMany("Roles")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("Settings.Domain.Entities.State", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Settings.Domain.Entities.TimeLog", b =>
                {
                    b.HasOne("Settings.Domain.Entities.Role", "role")
                        .WithMany("TimeLogs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Settings.Domain.Entities.BusinessType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Category", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Company", b =>
                {
                    b.Navigation("BusinessLocations");

                    b.Navigation("Clients");

                    b.Navigation("Departments");

                    b.Navigation("Designations");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Settings.Domain.Entities.CustomQuestionCategory", b =>
                {
                    b.Navigation("recruitCustomQuestionSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.CustomQuestionType", b =>
                {
                    b.Navigation("recruitCustomQuestionSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Department", b =>
                {
                    b.Navigation("Designations");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Designation", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Settings.Domain.Entities.JobApplicationCategory", b =>
                {
                    b.Navigation("RecruitJobApplicationStatusSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.JobApplicationPosition", b =>
                {
                    b.Navigation("RecruitJobApplicationStatusSettings");
                });

            modelBuilder.Entity("Settings.Domain.Entities.ProjectReminderPerson", b =>
                {
                    b.Navigation("ProjectSetting");
                });

            modelBuilder.Entity("Settings.Domain.Entities.Role", b =>
                {
                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("Settings.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
